# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app
COPY PDF-Pilot_v1/src/server.py PDF-Pilot_v1/src/HandoutAssistant.py requirements.txt .env ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the backend port
EXPOSE 5001

# Run the server
CMD ["python", "server.py"]
